smallboy = """MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWNKXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMKxoccloOXMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMN0ddOXd::;:o0WMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMXxk0XXx:,,;:cd0XWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMN0dokko,     .:okO0XMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMXkol:,..         '::odxKWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMNk:::;:'            .:c,,lkNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWKkd:',:;.              .',:::l0WMMMMMMMMMMMMMMM
MMMMMMMMMMMNkolc::;.                  ,c:''lOO0NMMMMMMMMMMMM
MMMMMMMMMWKoll;,;'...'..   ..          .'.,oddlo0NMMMMMMMMMM
MMMMMMMNOxkkkoc:,,;:,,:;,....   ...,,;'',',:'.,'.,dXWMMMMMMM
MMMMMMXxd0WXxkOd,..,,,;;;:,. ..;;',,''..,:::l:'...:dxxONMMMM
MMMMWKdkKOddkOl'......';,,ol'..;c::;,'..''.,cc.  ..;oOOOXWMM
MMMMWXXO:.  ''....''..',:lo'    .:dc;'.......,;.'''. .;oKWMM
MMMMMMOc:;..,'..';;,.  'kK:  'c. .lo'..,;ccc'.,;'''..  ;0MMM
MMMMMXddl'.....''.      co.  ..   ',  ..:Ok;. ..',. . .cKMMM
MMMMMNKx..'.  ;l',;.    .,.       ..     dO'  .. ;;lxc,lXMMM
MMMMMMWo  ,'  ;:,kx'...'lx:..  ..'ok:..'c0X:  .. ,ckMWNXWMMM
MMMMMMWOoodd:.;..ONd'lXNWNo...':ONW0;..cKMX;  .':ox0MMMMMMMM
MMMMMMMMMMW0c,.  o0, :XMWx.  .;cOWNl  .'lXk.   'kNMMMMMMMMMM
MMMMMMMMMMNc     .:. .;dO;   .,,l00,    'o,  ''.oWMMMMMMMMMM
MMMMMMMMMMWd.     ...   '.       .c.   .'.   ;l,xMMMMMMMMMMM
MMMMMMMMMMWO:.      .,,,:'       .l:.',.  .  'dONMMMMMMMMMMM
MMMMMMMMMMMWNk'   ...'';odoc:;;:lxOdc;.      '0MMMMMMMMMMMMM
MMMMMMMMMMMMMWo.. ;oxk,   .,ol;,'':,,dc,. .'.oNMMMMMMMMMMMMM
MMMMMMMMMMMMW0::d,:KW0'    .kOoc. cOOXNx..cxONMMMMMMMMMMMMMM
MMMMMMMMMMMMNOOXko0WMNc.:, .xMMNo.oWMMKc;xNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNWMMMMOo0Xo;OMMMXkKMMMKOXMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWWMMNNWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"""

bogboy = """MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOoclooddd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc;cdd::clccdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXko;cKMXo,'...:ookNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdclcdXMMWXkdddc'':lxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc:0MMMMW0c.   .:xo,ckkOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0llKNK00Ol.       'olcOX0kOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOolddlcoo;.          .';coO0kxONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx:coo;'....              .:l,.:OockXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMXd,;oo;.;l'       .           'l;.cx;.:oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMWK:.,xc..cdc.       .     .      'xx,..,occKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNOoc:,',.'okc.                       .::;;,:loldXMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWOoldxd,.':l;.                            'lo,.',.:KWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMXlckOl;;lddc'                             .:loxd:. .:oddkXMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWK:.cc. 'clc'.              .. . ....         ';;,..,ok0KOl:xNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNd,,lo;,,,'',,...,;::'.   ...                   .:;. .:c:oO0o,oKWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWKxloONWXxlcc;;cooc;'..,;'.....'''.    .....,::;::..', .;do.  .'...,ckNMMMMMMMMMMMMMMM
MMMMMMMMMMMMW0c,cONKd:''',;:,,,::;;';ll:::;.        .....','.';:,';c'.,.,;...,;'   'lOXWWMMMMMMMMMMM
MMMMMMMMMMMNx;c0WMMXdokXNNKo'..':::;,;::::cl;      'ol,.'::'..,'...:cclc:::,..''. .lxc::cdONMMMMMMMM
MMMMMMMMMMNo;xNMMMMMMWWMXd:..'.  .'. .,,'..,oo:;;;;:dxc,.;:;;,,'..',;'';lx0O:.    .;oxOOkxloONMMMMMM
MMMMMMMMWOl:xNXOoc::cdOd,..  .'. .','';::'':x0x;....:ol:;;,','.. .,;'. ..',,.   .'.   ,xKWN0xkNMMMMM
MMMMMMMMNkONW0;.     ''.... ...'. ..''';,''ckl        .dKOo:;;.. .,'. .  ..;dc.  :;..   .,cd0WMMMMMM
MMMMMMMMMWMMK:.'.  .;',,......;ll:'.....,lxxl.   ...   'odl;;:;'..,,.......',;::..,'c,      ;kNMMMMM
MMMMMMMMMMWk'.:o;..,'....';',llol'..   .dNM0'    lXd.   ;0Nd.. .,,'c::llc..;c,....;.''..   .lKWMMMMM
MMMMMMMMMMK:,kklc. .,c:''..'c,         .lKWx.    ;o:     ok.    ;;,kKkOko'  .':c..c.  .;. .,c0MMMMMM
MMMMMMMMMNl:KK:....''.  ..',.      ..    ;Oc             ;:     .. ,0Nx'.      ..;o.  .   .;l0MMMMMM
MMMMMMMMMNkONx. .'.    .looc  :c.        .c'             .,         cNX:    .'   'o, ckc'. .oXMMMMMM
MMMMMMMMMMMM0,   co.   .oo:'.oKc         .l'             'l.        :XMx.    ,'   oo;OMWN0lcxXMMMMMM
MMMMMMMMMMMM0'   .o,    ;k:.cNXc. ..   ..oKx,...      ..'dXk:'...,;cOWMO.    .,. .oc,OMMMMWWMMMMMMMM
MMMMMMMMMMMMO.....;o'   ,o' cNMXOc':x000XWMW0l,.....'o0KNWMXo,...:0WMMMk.    .;. ,l'.kMMMMMMMMMMMMMM
MMMMMMMMMMMMNkOXXOkKOc;;l;  ,KMMO' .dMMMMMM0;    ..'cOWMMMNl   .''dWMMWd.     ;l;xKkONMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWOlc;'.  .kMNc   oWMMMMNl     ;odxONMMMO.   ,c,;kWMX;      .dKXMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMNd'..      ;Kk.   :KWMMMk.      ...cKMMNl    ..  '0Wd.       .kWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM0'          co.    .:oKNc      ,loddkXMK,        'Ok.    ,o,  oWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMNo.          ,,       ,o'            'kO.        ;l.     :Ko .xMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMK,           .,'     .'.             ,o.      ';,.      .kd.;KMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMNo'.           .;c:'. .,.             'o,   .:l:.  .'.   .xxl0MMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMNO00: ..         .,loxOKk;.          ,xN0olll;.    ..     oNWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNo.      .;. '. .,cx0XKOdlccccldONWXOd:,.            .dWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWo      oO',Ox.    ..;clloooooolc:c' .dk' .'    .'. ,KMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMx. ''  :kd0MNl        .co,      .dk'.xNd;o:    co.'OWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMK: ,0O' :XMMM0'        .kWx;::.   lNkoKMWNK;   cxclKWMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMXx;'cKWd..kWMMMO,  ,,    .kMWNWX:  .kMMMMMMWx. .cKWNWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMXOOKWWO;:0WMMMMMO' :x;    cNMMMWO; .OMMMMMWk. ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMXKNMMMMMMMK; cXXOc  cNMMMMMk'lNMMMMMXlckXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkdXMMM0;cKMMMMMMKkXMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"""
